# Generated by Django 3.1.1 on 2020-10-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=150)),
                ('lastName', models.CharField(max_length=150)),
                ('emailAddress', models.EmailField(max_length=150)),
                ('displayName', models.CharField(max_length=20)),
                ('homePhone', models.CharField(max_length=15)),
            ],
        ),
    ]
